services:
  backend:
    build: ./backend
    volumes:
      - api-data:/data
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  api-data:
